export default function Head() {
  return (
    <>
      <title>Ron Philip</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="https://img.icons8.com/ios7/600/000000/r-key.png" />
    </>
  )
}
